### ISSUE TITLE
Startup script does not work

### ISSUE THREAD

**Issue by ethanuppal** [wojciech-kulik/FlashSpace#270]
### Captchas

- [x] I have read the [Design Decisions](https://github.com/wojciech-kulik/FlashSpace#-design-decisions) section in the README.
- [x] My issue is not about [support for agent apps](https://bit.ly/agent-app-support).

### Steps to reproduce

1. Create a file with the following contents:
```sh
#!/bin/sh

brew services start sketchybar
```
2. In the integrations section of the app, for startup script write "/bin/sh \<absolute path to the script\>".
3. Quit the app
4. `brew services stop sketchybar`
5. Start the app

sketchybar will not run. 

6. Run `/bin/sh <absolute path to the script>`

sketchybar will run.

### Actual result

The startup script does not run.

### Expected result

The startup script should be run.

### Version

1.0.0

### Your config

```toml
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = false
checkForUpdatesAutomatically = true
enableFocusManagement = true
enableIntegrations = true
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSwipeGestures = false
enableWorkspaceTransitions = false
focusDown = 'cmd+ctrl+opt+j'
focusFrontmostWindow = true
focusLeft = 'cmd+ctrl+opt+h'
focusNextWorkspaceApp = 'cmd+ctrl+opt+n'
focusNextWorkspaceWindow = 'cmd+ctrl+opt+shift+n'
focusPreviousWorkspaceApp = 'cmd+ctrl+opt+p'
focusPreviousWorkspaceWindow = 'cmd+ctrl+opt+shift+p'
focusRight = 'cmd+ctrl+opt+l'
focusUp = 'cmd+ctrl+opt+k'
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
runScriptOnLaunch = '/bin/sh /Users/ethan/.local/bin/flashspace-launch.sh '
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = '/opt/homebrew/bin/sketchybar --trigger flashspace_workspace_change WORKSPACE=$WORKSPACE'
showFloatingNotifications = true
showMenuBarTitle = true
showSpaceControl = 'cmd+ctrl+opt+space'
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
toggleTheFocusedAppFloating = 'cmd+ctrl+opt+shift+['
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999

[[floatingApps]]
bundleIdentifier = 'com.apple.finder'
iconPath = '/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns'
name = 'Finder'

[[floatingApps]]
bundleIdentifier = 'pl.wojciechkulik.FlashSpace'
iconPath = '/Applications/FlashSpace.app/Contents/Resources/AppIcon.icns'
name = 'FlashSpace'

[[floatingApps]]
bundleIdentifier = 'com.apple.MobileSMS'
iconPath = '/System/Applications/Messages.app/Contents/Resources/AppIcon.icns'
name = 'Messages'
```
