### ISSUE TITLE
Closing a focused floating window locks movement

### ISSUE THREAD

**Issue by ethanuppal** [wojciech-kulik/FlashSpace#310]
### Captchas

- [x] I have read the [Design Decisions](https://github.com/wojciech-kulik/FlashSpace#-design-decisions) section in the README.
- [x] My issue is not about [support for agent apps](https://bit.ly/agent-app-support).

### Steps to reproduce

1. Create a new workspace
2. Assign a regular app to the workspace
3. Open a floating app in the workspace
4. Focus the floating app
5. Close the floating app
6. Use something like the "next window" keybind to try to focus the regular app

### Actual result

The app is not focusable.

### Expected result

To focus the app, either at step 5 (preferably) or step 6

### Version

1.0.0

### Your config

```toml
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = false
checkForUpdatesAutomatically = true
enableFocusManagement = true
enableIntegrations = true
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSwipeGestures = true
enableWorkspaceTransitions = false
focusDown = 'cmd+ctrl+opt+j'
focusFrontmostWindow = true
focusLeft = 'cmd+ctrl+opt+h'
focusNextWorkspaceApp = 'cmd+ctrl+opt+n'
focusNextWorkspaceWindow = 'cmd+ctrl+opt+shift+n'
focusPreviousWorkspaceApp = 'cmd+ctrl+opt+p'
focusPreviousWorkspaceWindow = 'cmd+ctrl+opt+shift+p'
focusRight = 'cmd+ctrl+opt+l'
focusUp = 'cmd+ctrl+opt+k'
keepUnassignedAppsOnSwitch = false
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
restoreHiddenAppsOnSwitch = true
runScriptOnLaunch = '/bin/sh /Users/ethan/.local/bin/flashspace-launch.sh '
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = '/opt/homebrew/bin/sketchybar --trigger flashspace_workspace_change WORKSPACE=$WORKSPACE'
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = true
showSpaceControl = 'cmd+ctrl+opt+space'
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'none'
swipeLeft4FingerAction = 'nextWorkspace'
swipeRight3FingerAction = 'none'
swipeRight4FingerAction = 'previousWorkspace'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
toggleTheFocusedAppFloating = 'cmd+ctrl+opt+shift+['
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999

[[floatingApps]]
bundleIdentifier = 'com.apple.finder'
iconPath = '/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns'
name = 'Finder'

[[floatingApps]]
bundleIdentifier = 'pl.wojciechkulik.FlashSpace'
iconPath = '/Applications/FlashSpace.app/Contents/Resources/AppIcon.icns'
name = 'FlashSpace'

[[floatingApps]]
bundleIdentifier = 'com.apple.MobileSMS'
iconPath = '/System/Applications/Messages.app/Contents/Resources/AppIcon.icns'
name = 'Messages'

[[floatingApps]]
bundleIdentifier = 'com.apple.Dictionary'
iconPath = '/System/Applications/Dictionary.app/Contents/Resources/AppIconLoc.icns'
name = 'Dictionary'

[[floatingApps]]
bundleIdentifier = 'com.apple.systempreferences'
iconPath = '/System/Applications/System Settings.app/Contents/Resources/PrefApp.icns'
name = 'System Settings'

[[floatingApps]]
bundleIdentifier = 'com.objective-see.lulu.app'
iconPath = '/Applications/LuLu.app/Contents/Resources/AppIcon.icns'
name = 'LuLu'
```
